### ISSUE TITLE
Erraticly different results with functional tests (chapter 6) - selenium chrome

### ISSUE THREAD

**Issue by tychovk** [hjwp/book-example#12]
Hi everyone,

Right now, Firefox doesn't seem to be working with Selenium. So, I tried Chrome browser, and it seems to work alright, until chapter 5-6. Here, I'm getting different results from running `python3 manage.py test functional_tests`, alternating between:

```
======================================================================
FAIL: test_can_start_a_list_and_retrieve_it_later (functional_tests.tests.NewVisitorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/diego/python/testtut/superlists/functional_tests/tests.py", line 46, in test_can_start_a_list_and_retrieve_it_later
    self.assertRegex(unique_list_url, '/lists/.+')
AssertionError: Regex didn't match: '/lists/.+' not found in 'http://localhost:8081/'
```

```
FAIL: test_can_start_a_list_and_retrieve_it_later (functional_tests.tests.NewVisitorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/diego/python/testtut/superlists/functional_tests/tests.py", line 58, in test_can_start_a_list_and_retrieve_it_later
    self.check_for_rows_in_list_table('2: Use peacock feather to make a fly')
  File "/home/diego/python/testtut/superlists/functional_tests/tests.py", line 20, in check_for_rows_in_list_table
    self.assertIn(row_text, [row.text for row in rows])
AssertionError: '2: Use peacock feather to make a fly' not found in ['1: Buy peacock feathers']
```

and 
```
======================================================================
ERROR: test_can_start_a_list_and_retrieve_it_later (functional_tests.tests.NewVisitorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/diego/python/testtut/superlists/functional_tests/tests.py", line 57, in test_can_start_a_list_and_retrieve_it_later
    self.check_for_rows_in_list_table('1: Buy peacock feathers')
  File "/home/diego/python/testtut/superlists/functional_tests/tests.py", line 19, in check_for_rows_in_list_table
    rows = table.find_elements_by_tag_name('tr')
  File "/home/diego/python/testtut/TDDvenv/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py", line 210, in find_elements_by_tag_name
    return self.find_elements(by=By.TAG_NAME, value=name)
  File "/home/diego/python/testtut/TDDvenv/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py", line 490, in find_elements
    {"using": by, "value": value})['value']
  File "/home/diego/python/testtut/TDDvenv/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py", line 456, in _execute
    return self._parent.execute(command, params)
  File "/home/diego/python/testtut/TDDvenv/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/home/diego/python/testtut/TDDvenv/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=51.0.2704.84)
  (Driver info: chromedriver=2.9.248304,platform=Linux 4.4.0-24-generic x86_64)
```

I have a feeling that it's something like the browser not being able to keep up with the fast demands from Selenium. I've dug a bit into what other solutions were, but there doesn't seem to be an easy one.

Just a question: is there something I can do about this, or is this going to be tackled in a later chapter?

Thank you, and thank you for the great, enthusiastic, and gluing-to-the-screen tutorial!

**Comment by tychovk** [comment]
I don't understand anymore. Sometimes it goes all the way to the end, and says:

```
======================================================================
FAIL: test_can_start_a_list_and_retrieve_it_later (functional_tests.tests.NewVisitorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/diego/python/testtut/superlists/functional_tests/tests.py", line 90, in test_can_start_a_list_and_retrieve_it_later
    self.fail('Finish the test!')
AssertionError: Finish the test!

----------------------------------------------------------------------
Ran 1 test in 7.657s


```

**Comment by Shih-Po** [comment]
I had the same issue like yours at the end of chapter-05, I add an easy wait after functinoal_tests send an ENTER keys, and it works.

#### functional_tests/tests.py
```
        [...]
        # She inputs 'Buy a basketball'
        inputbox.send_keys('Buy a basketball')

        # While she presses enter, website renews and lists out:
        # 1. Buy a basketball
        inputbox.send_keys(Keys.ENTER)
        self.browser.implicitly_wait(3)

        self.check_for_row_in_list_table('1: Buy a basketball')

        # Now there still has an text bar to let her add other todos
        # She inputs 'Call friends to play basketball'
        inputbox = self.browser.find_element_by_id('id_new_item')
        inputbox.send_keys('Call friends to play basketball')
        inputbox.send_keys(Keys.ENTER)
        self.browser.implicitly_wait(3)
        [...]
```

**Comment by hjwp** [comment]
Hi gang I'm really sorry but I can't debug issues with the book here.  If you still need help, can I ask you to re-post your question, either to the mailing list here https://groups.google.com/forum/#!forum/obey-the-testing-goat-book or as a comment on one of the online versions' chapters http://www.obeythetestinggoat.com/pages/book.html
